### ISSUE TITLE
Can't deepcopy a ParameterSet

### ISSUE THREAD

**Issue by laurentperrinet** [laurentperrinet/NeuroTools#33]
{{{
# !python

from copy import deepcopy
ps2 = deepcopy(ps)
Traceback (most recent call last):
  File "test_parameters.py", line 143, in test_diff_inside_list
    ps2 = deepcopy(ps)
  File "/Library/Frameworks/Python.framework/Versions/2.5.2001/lib/python2.5/copy.py", line 171, in deepcopy
    copier = getattr(x, "**deepcopy**", None)
  File "/Users/andrew/Work/NeuroTools/parameters.py", line 372, in **getattr**
    return self[name]
  File "/Users/andrew/Work/NeuroTools/parameters.py", line 387, in **getitem**
    return dict.**getitem**(self,name)
KeyError: '**deepcopy**'

---
### Imported from Trac ticket:32

**Opened**: 2008-10-31 13:45:29
**Last modified**: 2008-11-03 17:52:16
**Component**: parameters
**Priority**: major
**Owner**: 
**Reporter**: apdavison

**Comment by laurentperrinet** [comment]
**apdavison wrote on 2008-11-03 17:52:16:**

Fixed in r274
