### ISSUE TITLE
import error in intervals

### ISSUE THREAD

**Issue by laurentperrinet** [laurentperrinet/NeuroTools#54]
checking for the tests:
{{{
manga:test lup$ python test_spikes.py 
Traceback (most recent call last):
  File "test_spikes.py", line 6, in <module>
    import NeuroTools.signals.spikes as spikes
  File "/Users/lup/lib/python2.6/site-packages/NeuroTools/signals/**init**.py", line 31, in <module>
    from spikes import *
  File "/Users/lup/lib/python2.6/site-packages/NeuroTools/signals/spikes.py", line 33, in <module>
    from intervals import *
  File "/Users/lup/lib/python2.6/site-packages/NeuroTools/signals/intervals.py", line 4, in <module>
    from interval import interval
ImportError: cannot import name interval
}}}

simply in python :
{{{
## In [1]: from interval import interval

ImportError                               Traceback (most recent call last)

/Users/lup/sci/neuralensemble/NeuroTools/trunk/test/<ipython console> in <module>()

ImportError: cannot import name interval
}}} 
but 
{{{
In [2]: from interval import *

}}}

---
### Imported from Trac ticket:53

**Opened**: 2009-04-14 13:50:15
**Last modified**: 2009-06-09 10:12:43
**Component**: signals
**Priority**: major
**Owner**: pierre
**Reporter**: LaurentPerrinet

**Comment by laurentperrinet** [comment]
**pierre wrote on 2009-06-09 10:12:43:**

I didn't see this error, but it seems to me that this is now fixed. Interval is by the way not really used now, but it should be in the future....
