### ISSUE TITLE
import django  in datastore

### ISSUE THREAD

**Issue by laurentperrinet** [laurentperrinet/NeuroTools#55]
there's no dependency checking when importing django in datastore, for instance:
{{{
manga:test lup$ python test_datastore.py 
Traceback (most recent call last):
  File "test_datastore.py", line 9, in <module>
    from NeuroTools.datastore import *
  File "/Users/lup/lib/python2.6/site-packages/NeuroTools/datastore/**init**.py", line 42, in <module>
    from django_orm import DjangoORMDataStore
  File "/Users/lup/lib/python2.6/site-packages/NeuroTools/datastore/django_orm/**init**.py", line 7, in <module>
    from django.conf import settings
ImportError: No module named django.conf
}}}

---
### Imported from Trac ticket:54

**Opened**: 2009-04-14 14:16:34
**Last modified**: 2009-04-21 14:38:47
**Component**: ALL
**Priority**: minor
**Owner**: apdavison
**Reporter**: LaurentPerrinet
**Keywords**: datastore

**Comment by laurentperrinet** [comment]
**apdavison wrote on 2009-04-21 14:38:47:**

Fixed in r394
